{% set name = "grib2io-interp" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/grib2io_interp-{{ version }}.tar.gz
  sha256: 922cf48f940d13cc083408ed429a8d735431c133b379660e7d4450ca30e5ae63

build:
  skip: true  # [win or py>=312]
  number: 1
  script_env:
    - IP_DIR={{ PREFIX }}
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - {{ stdlib('c') }}                   # [not win]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - nceplibs-ip >=5.1.0                 # [build_platform != target_platform]
    - numpy <2.0.0                        # [build_platform != target_platform]
    - pip                                 # [build_platform != target_platform]
    - python                              # [build_platform != target_platform]
    - setuptools >=61.0                   # [build_platform != target_platform]
  host:
    - nceplibs-ip >=5.1.0
    - numpy <2.0.0
    - pip
    - python
    - setuptools >=61.0
  run:
    - grib2io
    - nceplibs-ip >=5.1.0
    - python

test:
  imports:
    - grib2io_interp
  commands:
    - pip check
  requires:
    - pip
    - nceplibs-ip >=5.1.0

about:
  summary: Interpolation component for grib2io providing a Python interface to NCEPLIBS-ip
  license: MIT
  license_file: LICENSE
  home: https://pypi.org/project/grib2io-interp/

extra:
  recipe-maintainers:
    - TimothyCera-NOAA
    - EricEngle-NOAA
